version: '3.8'

services:
  # Development version with hot reload
  crm-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres-dev
    networks:
      - crm-dev-network
    restart: unless-stopped

  # PostgreSQL for development
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crm_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - crm-dev-network
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  crm-dev-network:
    driver: bridge
